# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 06:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170703_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': '\u0421\u0442\u0430\u0442\u0442\u044f', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0442\u0456'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='\u0421\u0442\u0432\u043e\u0440\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_comments_enabled',
            field=models.BooleanField(default=True, verbose_name='\u0427\u0438 \u043c\u043e\u0436\u043d\u0430 \u043a\u043e\u043c\u0435\u043d\u0442\u0443\u0432\u0430\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000, verbose_name='\u0422\u0435\u043a\u0441\u0442 (\u0434\u043e 10 000 \u0441\u0438\u043c\u0432\u043e\u043b\u0456\u0432)'),
        ),
    ]
